version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py --user
      - sudo pip install --upgrade pip
      - pip install --user aws-sam-cli
      - pip install pipenv
      - pip install diagrams
      - pipenv install diagrams
      - pip install poetry
artifacts:
  files:
    - '**/*'
