[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Sébastien Eustace <sebastien@eustace.io>"]

[tool.poetry.dependencies]
python = "^3.6"
diagrams = "^0.13.1"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
diagrams = "^0.13.1"